// GENERATED by scripts/build-model-spectrum.mjs – do not edit by hand.
// Weighted practitioner/user evidence: score -100…+100 per model and task (credibility x quality x recency, same-source repeats damped,
// shrunk toward 0 when evidence is thin); effort = level the weighted verdicts point to for that model.
export type SpectrumCell = { score: number; evidence: 'strong' | 'medium' | 'weak'; mass: number; sources: number; statements: number };
export type EffortCell = { effort: string; avoidFrom: string | null; evidence: 'strong' | 'medium' | 'weak'; mass: number; sources: number };
export const SPECTRUM_META = {"builtAt":"2026-09-26","statements":668,"effortStatements":171,"droppedStatements":2,"droppedEffort":4} as const;
export const MODEL_SPECTRUM: Record<string, Record<string, SpectrumCell>> = {
 "claude-sonnet-5": {
  "cost_speed": {
   "score": -78,
   "evidence": "strong",
   "mass": 15.67,
   "sources": 15,
   "statements": 19
  },
  "frontend_ui": {
   "score": -55,
   "evidence": "weak",
   "mass": 2.44,
   "sources": 3,
   "statements": 3
  },
  "agentic_terminal": {
   "score": 3,
   "evidence": "medium",
   "mass": 5.8,
   "sources": 6,
   "statements": 7
  },
  "writing_docs": {
   "score": -50,
   "evidence": "weak",
   "mass": 2.78,
   "sources": 4,
   "statements": 5
  },
  "code_review": {
   "score": 0,
   "evidence": "medium",
   "mass": 3.84,
   "sources": 3,
   "statements": 4
  },
  "research_knowledge": {
   "score": -27,
   "evidence": "medium",
   "mass": 6.49,
   "sources": 5,
   "statements": 6
  },
  "implementation": {
   "score": 57,
   "evidence": "medium",
   "mass": 7.95,
   "sources": 12,
   "statements": 14
  },
  "debugging": {
   "score": -28,
   "evidence": "weak",
   "mass": 2.11,
   "sources": 3,
   "statements": 3
  },
  "simple_edits": {
   "score": 21,
   "evidence": "weak",
   "mass": 0.54,
   "sources": 1,
   "statements": 1
  },
  "architecture_planning": {
   "score": -29,
   "evidence": "weak",
   "mass": 0.8,
   "sources": 1,
   "statements": 1
  }
 },
 "claude-opus-5-5": {
  "cost_speed": {
   "score": 34,
   "evidence": "strong",
   "mass": 20.09,
   "sources": 15,
   "statements": 22
  },
  "architecture_planning": {
   "score": 16,
   "evidence": "medium",
   "mass": 7.74,
   "sources": 7,
   "statements": 9
  },
  "agentic_terminal": {
   "score": 22,
   "evidence": "strong",
   "mass": 17.81,
   "sources": 12,
   "statements": 17
  },
  "frontend_ui": {
   "score": 74,
   "evidence": "medium",
   "mass": 5.64,
   "sources": 4,
   "statements": 4
  },
  "writing_docs": {
   "score": 78,
   "evidence": "strong",
   "mass": 11.52,
   "sources": 8,
   "statements": 12
  },
  "implementation": {
   "score": 69,
   "evidence": "strong",
   "mass": 21.8,
   "sources": 14,
   "statements": 23
  },
  "code_review": {
   "score": 70,
   "evidence": "medium",
   "mass": 4.63,
   "sources": 4,
   "statements": 4
  },
  "research_knowledge": {
   "score": 12,
   "evidence": "strong",
   "mass": 12.61,
   "sources": 7,
   "statements": 10
  },
  "debugging": {
   "score": -5,
   "evidence": "weak",
   "mass": 2.96,
   "sources": 3,
   "statements": 3
  },
  "refactoring_migration": {
   "score": 55,
   "evidence": "weak",
   "mass": 2.48,
   "sources": 3,
   "statements": 3
  },
  "simple_edits": {
   "score": -25,
   "evidence": "weak",
   "mass": 0.68,
   "sources": 1,
   "statements": 1
  }
 },
 "claude-opus-5": {
  "debugging": {
   "score": -50,
   "evidence": "medium",
   "mass": 6.4,
   "sources": 4,
   "statements": 6
  },
  "writing_docs": {
   "score": -76,
   "evidence": "medium",
   "mass": 6.34,
   "sources": 6,
   "statements": 8
  },
  "code_review": {
   "score": -27,
   "evidence": "weak",
   "mass": 1.46,
   "sources": 2,
   "statements": 2
  },
  "implementation": {
   "score": -14,
   "evidence": "strong",
   "mass": 16.62,
   "sources": 14,
   "statements": 19
  },
  "refactoring_migration": {
   "score": 55,
   "evidence": "weak",
   "mass": 2.4,
   "sources": 1,
   "statements": 1
  },
  "architecture_planning": {
   "score": -16,
   "evidence": "medium",
   "mass": 3.13,
   "sources": 5,
   "statements": 6
  },
  "agentic_terminal": {
   "score": -71,
   "evidence": "medium",
   "mass": 4.97,
   "sources": 3,
   "statements": 7
  },
  "cost_speed": {
   "score": -38,
   "evidence": "weak",
   "mass": 2.94,
   "sources": 3,
   "statements": 4
  },
  "simple_edits": {
   "score": -15,
   "evidence": "weak",
   "mass": 1.86,
   "sources": 2,
   "statements": 2
  },
  "research_knowledge": {
   "score": 22,
   "evidence": "weak",
   "mass": 2.31,
   "sources": 2,
   "statements": 2
  },
  "frontend_ui": {
   "score": 35,
   "evidence": "weak",
   "mass": 1.09,
   "sources": 2,
   "statements": 2
  }
 },
 "gpt-6-sol": {
  "writing_docs": {
   "score": 55,
   "evidence": "weak",
   "mass": 2.4,
   "sources": 2,
   "statements": 2
  },
  "agentic_terminal": {
   "score": 35,
   "evidence": "medium",
   "mass": 4.78,
   "sources": 4,
   "statements": 4
  },
  "implementation": {
   "score": -32,
   "evidence": "strong",
   "mass": 9.53,
   "sources": 5,
   "statements": 10
  },
  "cost_speed": {
   "score": 34,
   "evidence": "strong",
   "mass": 17.43,
   "sources": 13,
   "statements": 17
  },
  "research_knowledge": {
   "score": -77,
   "evidence": "medium",
   "mass": 6.72,
   "sources": 7,
   "statements": 7
  },
  "code_review": {
   "score": 54,
   "evidence": "weak",
   "mass": 2.34,
   "sources": 2,
   "statements": 2
  },
  "architecture_planning": {
   "score": -6,
   "evidence": "weak",
   "mass": 1.16,
   "sources": 2,
   "statements": 2
  },
  "debugging": {
   "score": -40,
   "evidence": "weak",
   "mass": 1.36,
   "sources": 1,
   "statements": 1
  }
 },
 "gpt-5-5": {
  "writing_docs": {
   "score": 32,
   "evidence": "weak",
   "mass": 0.96,
   "sources": 1,
   "statements": 1
  },
  "debugging": {
   "score": -32,
   "evidence": "weak",
   "mass": 0.96,
   "sources": 1,
   "statements": 1
  },
  "implementation": {
   "score": -12,
   "evidence": "medium",
   "mass": 4.88,
   "sources": 5,
   "statements": 6
  },
  "agentic_terminal": {
   "score": 53,
   "evidence": "weak",
   "mass": 2.22,
   "sources": 2,
   "statements": 2
  },
  "architecture_planning": {
   "score": 47,
   "evidence": "weak",
   "mass": 1.74,
   "sources": 2,
   "statements": 2
  },
  "code_review": {
   "score": 10,
   "evidence": "weak",
   "mass": 0.22,
   "sources": 1,
   "statements": 1
  },
  "research_knowledge": {
   "score": 21,
   "evidence": "weak",
   "mass": 0.54,
   "sources": 1,
   "statements": 1
  }
 },
 "claude-fable-5-1": {
  "implementation": {
   "score": 48,
   "evidence": "strong",
   "mass": 17.99,
   "sources": 8,
   "statements": 16
  },
  "agentic_terminal": {
   "score": 43,
   "evidence": "strong",
   "mass": 11.91,
   "sources": 7,
   "statements": 13
  },
  "writing_docs": {
   "score": 27,
   "evidence": "medium",
   "mass": 4.87,
   "sources": 5,
   "statements": 8
  },
  "simple_edits": {
   "score": -37,
   "evidence": "weak",
   "mass": 1.2,
   "sources": 1,
   "statements": 1
  },
  "code_review": {
   "score": 47,
   "evidence": "medium",
   "mass": 6.24,
   "sources": 3,
   "statements": 4
  },
  "debugging": {
   "score": -8,
   "evidence": "medium",
   "mass": 3.8,
   "sources": 4,
   "statements": 5
  },
  "refactoring_migration": {
   "score": -37,
   "evidence": "weak",
   "mass": 1.2,
   "sources": 1,
   "statements": 1
  },
  "architecture_planning": {
   "score": 65,
   "evidence": "medium",
   "mass": 3.79,
   "sources": 7,
   "statements": 10
  },
  "frontend_ui": {
   "score": -10,
   "evidence": "weak",
   "mass": 2.89,
   "sources": 3,
   "statements": 4
  },
  "cost_speed": {
   "score": -8,
   "evidence": "strong",
   "mass": 9.67,
   "sources": 9,
   "statements": 11
  },
  "research_knowledge": {
   "score": 33,
   "evidence": "weak",
   "mass": 2.99,
   "sources": 3,
   "statements": 4
  }
 },
 "gpt-6-astra": {
  "writing_docs": {
   "score": 59,
   "evidence": "medium",
   "mass": 4.19,
   "sources": 4,
   "statements": 4
  },
  "agentic_terminal": {
   "score": 42,
   "evidence": "strong",
   "mass": 20.77,
   "sources": 15,
   "statements": 18
  },
  "frontend_ui": {
   "score": 18,
   "evidence": "medium",
   "mass": 3.54,
   "sources": 4,
   "statements": 5
  },
  "code_review": {
   "score": 53,
   "evidence": "medium",
   "mass": 11.02,
   "sources": 4,
   "statements": 10
  },
  "cost_speed": {
   "score": -21,
   "evidence": "strong",
   "mass": 19.48,
   "sources": 9,
   "statements": 17
  },
  "architecture_planning": {
   "score": 70,
   "evidence": "medium",
   "mass": 4.76,
   "sources": 3,
   "statements": 3
  },
  "implementation": {
   "score": 51,
   "evidence": "strong",
   "mass": 13.63,
   "sources": 10,
   "statements": 17
  },
  "debugging": {
   "score": -44,
   "evidence": "weak",
   "mass": 1.6,
   "sources": 1,
   "statements": 1
  },
  "research_knowledge": {
   "score": 39,
   "evidence": "medium",
   "mass": 3.47,
   "sources": 4,
   "statements": 5
  },
  "simple_edits": {
   "score": 25,
   "evidence": "weak",
   "mass": 0.68,
   "sources": 1,
   "statements": 1
  }
 },
 "gpt-5-6-sol": {
  "debugging": {
   "score": 52,
   "evidence": "weak",
   "mass": 2.21,
   "sources": 1,
   "statements": 2
  },
  "implementation": {
   "score": 6,
   "evidence": "strong",
   "mass": 9.31,
   "sources": 6,
   "statements": 7
  },
  "writing_docs": {
   "score": 32,
   "evidence": "weak",
   "mass": 0.96,
   "sources": 1,
   "statements": 1
  },
  "research_knowledge": {
   "score": 55,
   "evidence": "strong",
   "mass": 9.14,
   "sources": 7,
   "statements": 7
  },
  "cost_speed": {
   "score": 49,
   "evidence": "strong",
   "mass": 12.44,
   "sources": 9,
   "statements": 10
  },
  "code_review": {
   "score": 18,
   "evidence": "strong",
   "mass": 10.83,
   "sources": 6,
   "statements": 6
  },
  "agentic_terminal": {
   "score": 17,
   "evidence": "strong",
   "mass": 10.53,
   "sources": 7,
   "statements": 7
  },
  "architecture_planning": {
   "score": 29,
   "evidence": "weak",
   "mass": 0.8,
   "sources": 1,
   "statements": 1
  },
  "simple_edits": {
   "score": -21,
   "evidence": "weak",
   "mass": 0.54,
   "sources": 1,
   "statements": 1
  },
  "frontend_ui": {
   "score": 31,
   "evidence": "weak",
   "mass": 0.92,
   "sources": 1,
   "statements": 1
  }
 },
 "claude-sonnet-4-6": {
  "code_review": {
   "score": 57,
   "evidence": "weak",
   "mass": 2.6,
   "sources": 2,
   "statements": 2
  },
  "architecture_planning": {
   "score": 32,
   "evidence": "weak",
   "mass": 0.92,
   "sources": 1,
   "statements": 1
  },
  "cost_speed": {
   "score": -17,
   "evidence": "weak",
   "mass": 0.79,
   "sources": 2,
   "statements": 2
  },
  "implementation": {
   "score": 51,
   "evidence": "weak",
   "mass": 2.09,
   "sources": 3,
   "statements": 3
  },
  "research_knowledge": {
   "score": 39,
   "evidence": "weak",
   "mass": 1.28,
   "sources": 1,
   "statements": 1
  },
  "writing_docs": {
   "score": -29,
   "evidence": "weak",
   "mass": 0.8,
   "sources": 1,
   "statements": 1
  },
  "debugging": {
   "score": 38,
   "evidence": "weak",
   "mass": 1.2,
   "sources": 1,
   "statements": 1
  },
  "frontend_ui": {
   "score": 19,
   "evidence": "weak",
   "mass": 0.48,
   "sources": 1,
   "statements": 1
  }
 },
 "gpt-5-6-terra": {
  "code_review": {
   "score": 27,
   "evidence": "medium",
   "mass": 3.35,
   "sources": 2,
   "statements": 3
  },
  "cost_speed": {
   "score": 23,
   "evidence": "medium",
   "mass": 5.71,
   "sources": 11,
   "statements": 11
  },
  "research_knowledge": {
   "score": 33,
   "evidence": "medium",
   "mass": 4.27,
   "sources": 4,
   "statements": 4
  },
  "implementation": {
   "score": 14,
   "evidence": "medium",
   "mass": 5.36,
   "sources": 6,
   "statements": 7
  },
  "agentic_terminal": {
   "score": -15,
   "evidence": "weak",
   "mass": 1.63,
   "sources": 2,
   "statements": 2
  },
  "simple_edits": {
   "score": 21,
   "evidence": "weak",
   "mass": 0.54,
   "sources": 1,
   "statements": 1
  }
 },
 "claude-fable-5": {
  "implementation": {
   "score": 56,
   "evidence": "weak",
   "mass": 2.57,
   "sources": 2,
   "statements": 3
  },
  "writing_docs": {
   "score": 23,
   "evidence": "medium",
   "mass": 4.04,
   "sources": 6,
   "statements": 7
  },
  "refactoring_migration": {
   "score": 39,
   "evidence": "medium",
   "mass": 4.07,
   "sources": 4,
   "statements": 5
  },
  "frontend_ui": {
   "score": -1,
   "evidence": "medium",
   "mass": 3.45,
   "sources": 5,
   "statements": 5
  },
  "agentic_terminal": {
   "score": 53,
   "evidence": "weak",
   "mass": 2.79,
   "sources": 5,
   "statements": 5
  },
  "debugging": {
   "score": 55,
   "evidence": "weak",
   "mass": 2.4,
   "sources": 2,
   "statements": 2
  },
  "architecture_planning": {
   "score": 79,
   "evidence": "medium",
   "mass": 7.35,
   "sources": 12,
   "statements": 12
  },
  "code_review": {
   "score": 2,
   "evidence": "medium",
   "mass": 3.31,
   "sources": 4,
   "statements": 4
  },
  "cost_speed": {
   "score": -46,
   "evidence": "medium",
   "mass": 6.5,
   "sources": 8,
   "statements": 8
  },
  "research_knowledge": {
   "score": -52,
   "evidence": "weak",
   "mass": 2.16,
   "sources": 1,
   "statements": 1
  }
 },
 "claude-opus-4-8": {
  "implementation": {
   "score": 31,
   "evidence": "medium",
   "mass": 6.26,
   "sources": 4,
   "statements": 11
  },
  "agentic_terminal": {
   "score": 25,
   "evidence": "weak",
   "mass": 2.92,
   "sources": 3,
   "statements": 3
  },
  "research_knowledge": {
   "score": 46,
   "evidence": "weak",
   "mass": 1.68,
   "sources": 1,
   "statements": 1
  },
  "code_review": {
   "score": 37,
   "evidence": "weak",
   "mass": 1.18,
   "sources": 2,
   "statements": 2
  },
  "writing_docs": {
   "score": 18,
   "evidence": "weak",
   "mass": 2.38,
   "sources": 2,
   "statements": 4
  },
  "cost_speed": {
   "score": -7,
   "evidence": "medium",
   "mass": 3.44,
   "sources": 2,
   "statements": 3
  },
  "simple_edits": {
   "score": 29,
   "evidence": "weak",
   "mass": 0.8,
   "sources": 1,
   "statements": 1
  },
  "debugging": {
   "score": -25,
   "evidence": "weak",
   "mass": 2.14,
   "sources": 2,
   "statements": 2
  }
 },
 "gpt-5-6-luna": {
  "simple_edits": {
   "score": 48,
   "evidence": "weak",
   "mass": 1.88,
   "sources": 2,
   "statements": 2
  },
  "cost_speed": {
   "score": 63,
   "evidence": "medium",
   "mass": 3.4,
   "sources": 4,
   "statements": 6
  },
  "implementation": {
   "score": 4,
   "evidence": "medium",
   "mass": 3.46,
   "sources": 2,
   "statements": 4
  },
  "agentic_terminal": {
   "score": 31,
   "evidence": "weak",
   "mass": 3.2,
   "sources": 1,
   "statements": 2
  },
  "code_review": {
   "score": 1,
   "evidence": "medium",
   "mass": 5.37,
   "sources": 2,
   "statements": 5
  }
 },
 "claude-haiku-4-5": {
  "simple_edits": {
   "score": 73,
   "evidence": "medium",
   "mass": 5.4,
   "sources": 6,
   "statements": 6
  },
  "architecture_planning": {
   "score": -35,
   "evidence": "weak",
   "mass": 1.08,
   "sources": 1,
   "statements": 1
  },
  "implementation": {
   "score": 62,
   "evidence": "medium",
   "mass": 3.32,
   "sources": 2,
   "statements": 2
  },
  "cost_speed": {
   "score": 39,
   "evidence": "medium",
   "mass": 5.02,
   "sources": 5,
   "statements": 8
  },
  "research_knowledge": {
   "score": -24,
   "evidence": "weak",
   "mass": 2.4,
   "sources": 4,
   "statements": 4
  },
  "writing_docs": {
   "score": 29,
   "evidence": "weak",
   "mass": 0.8,
   "sources": 1,
   "statements": 1
  }
 },
 "gpt-6-luna": {
  "cost_speed": {
   "score": 58,
   "evidence": "strong",
   "mass": 11.99,
   "sources": 9,
   "statements": 12
  },
  "implementation": {
   "score": 50,
   "evidence": "weak",
   "mass": 2,
   "sources": 2,
   "statements": 2
  },
  "agentic_terminal": {
   "score": -55,
   "evidence": "weak",
   "mass": 2.4,
   "sources": 1,
   "statements": 1
  },
  "research_knowledge": {
   "score": 25,
   "evidence": "weak",
   "mass": 0.68,
   "sources": 1,
   "statements": 1
  }
 }
};
export const MODEL_EFFORT: Record<string, Record<string, EffortCell>> = {
 "claude-fable-5-1": {
  "general": {
   "effort": "xhigh",
   "avoidFrom": "max",
   "evidence": "strong",
   "mass": 16,
   "sources": 15
  },
  "agentic_terminal": {
   "effort": "xhigh",
   "avoidFrom": null,
   "evidence": "medium",
   "mass": 2.72,
   "sources": 2
  },
  "simple_edits": {
   "effort": "low",
   "avoidFrom": "high",
   "evidence": "weak",
   "mass": 1.92,
   "sources": 1
  },
  "architecture_planning": {
   "effort": "high",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.8,
   "sources": 1
  },
  "implementation": {
   "effort": "medium",
   "avoidFrom": "high",
   "evidence": "medium",
   "mass": 2.4,
   "sources": 2
  },
  "code_review": {
   "effort": "medium",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 1.6,
   "sources": 1
  }
 },
 "claude-fable-5": {
  "general": {
   "effort": "max",
   "avoidFrom": null,
   "evidence": "strong",
   "mass": 6.92,
   "sources": 10
  },
  "architecture_planning": {
   "effort": "high",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 1.36,
   "sources": 2
  },
  "implementation": {
   "effort": "xhigh",
   "avoidFrom": null,
   "evidence": "medium",
   "mass": 2.59,
   "sources": 3
  }
 },
 "claude-opus-5-5": {
  "general": {
   "effort": "medium",
   "avoidFrom": null,
   "evidence": "strong",
   "mass": 20.72,
   "sources": 10
  },
  "agentic_terminal": {
   "effort": "xhigh",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.8,
   "sources": 1
  }
 },
 "claude-opus-5": {
  "general": {
   "effort": "low",
   "avoidFrom": null,
   "evidence": "strong",
   "mass": 10.82,
   "sources": 9
  },
  "agentic_terminal": {
   "effort": "xhigh",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.96,
   "sources": 1
  },
  "simple_edits": {
   "effort": "low",
   "avoidFrom": "high",
   "evidence": "weak",
   "mass": 1.92,
   "sources": 1
  },
  "implementation": {
   "effort": "high",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 1.52,
   "sources": 2
  }
 },
 "claude-opus-4-8": {
  "agentic_terminal": {
   "effort": "xhigh",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.96,
   "sources": 1
  },
  "general": {
   "effort": "max",
   "avoidFrom": null,
   "evidence": "strong",
   "mass": 5.78,
   "sources": 12
  },
  "research_knowledge": {
   "effort": "high",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 1.6,
   "sources": 2
  },
  "implementation": {
   "effort": "max",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 1.28,
   "sources": 2
  },
  "refactoring_migration": {
   "effort": "high",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.56,
   "sources": 1
  },
  "architecture_planning": {
   "effort": "low",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.56,
   "sources": 1
  }
 },
 "claude-sonnet-5": {
  "general": {
   "effort": "low",
   "avoidFrom": "xhigh",
   "evidence": "strong",
   "mass": 9.42,
   "sources": 11
  },
  "agentic_terminal": {
   "effort": "xhigh",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.96,
   "sources": 1
  },
  "writing_docs": {
   "effort": "low",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.96,
   "sources": 1
  },
  "research_knowledge": {
   "effort": "low",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 1.2,
   "sources": 1
  }
 },
 "claude-sonnet-4-6": {
  "implementation": {
   "effort": "medium",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.96,
   "sources": 1
  },
  "general": {
   "effort": "medium",
   "avoidFrom": "xhigh",
   "evidence": "medium",
   "mass": 3.52,
   "sources": 5
  },
  "writing_docs": {
   "effort": "low",
   "avoidFrom": "xhigh",
   "evidence": "medium",
   "mass": 2.24,
   "sources": 2
  },
  "research_knowledge": {
   "effort": "medium",
   "avoidFrom": "high",
   "evidence": "weak",
   "mass": 1.12,
   "sources": 1
  },
  "code_review": {
   "effort": "high",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.64,
   "sources": 1
  }
 },
 "gpt-6-astra": {
  "agentic_terminal": {
   "effort": "medium",
   "avoidFrom": "ultra",
   "evidence": "medium",
   "mass": 2.64,
   "sources": 2
  },
  "general": {
   "effort": "medium",
   "avoidFrom": "xhigh",
   "evidence": "strong",
   "mass": 8.04,
   "sources": 10
  },
  "implementation": {
   "effort": "low",
   "avoidFrom": "medium",
   "evidence": "medium",
   "mass": 4.32,
   "sources": 3
  },
  "code_review": {
   "effort": "high",
   "avoidFrom": "xhigh",
   "evidence": "weak",
   "mass": 0.88,
   "sources": 1
  },
  "debugging": {
   "effort": "max",
   "avoidFrom": "ultra",
   "evidence": "weak",
   "mass": 0.88,
   "sources": 1
  }
 },
 "gpt-6-sol": {
  "research_knowledge": {
   "effort": "low",
   "avoidFrom": "medium",
   "evidence": "weak",
   "mass": 2.64,
   "sources": 1
  },
  "general": {
   "effort": "low",
   "avoidFrom": "ultra",
   "evidence": "medium",
   "mass": 4.64,
   "sources": 4
  },
  "debugging": {
   "effort": "max",
   "avoidFrom": "ultra",
   "evidence": "weak",
   "mass": 0.88,
   "sources": 1
  }
 },
 "gpt-6-luna": {
  "research_knowledge": {
   "effort": "high",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 5.28,
   "sources": 1
  },
  "general": {
   "effort": "max",
   "avoidFrom": null,
   "evidence": "strong",
   "mass": 6,
   "sources": 4
  },
  "agentic_terminal": {
   "effort": "xhigh",
   "avoidFrom": "max",
   "evidence": "weak",
   "mass": 1.6,
   "sources": 1
  }
 },
 "gpt-5-6-sol": {
  "agentic_terminal": {
   "effort": "medium",
   "avoidFrom": "ultra",
   "evidence": "strong",
   "mass": 6.71,
   "sources": 3
  },
  "general": {
   "effort": "high",
   "avoidFrom": "xhigh",
   "evidence": "strong",
   "mass": 12.54,
   "sources": 15
  },
  "frontend_ui": {
   "effort": "high",
   "avoidFrom": "xhigh",
   "evidence": "medium",
   "mass": 2.52,
   "sources": 2
  },
  "research_knowledge": {
   "effort": "max",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.79,
   "sources": 1
  },
  "debugging": {
   "effort": "max",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.79,
   "sources": 1
  },
  "implementation": {
   "effort": "high",
   "avoidFrom": null,
   "evidence": "medium",
   "mass": 5.12,
   "sources": 2
  },
  "code_review": {
   "effort": "high",
   "avoidFrom": "xhigh",
   "evidence": "weak",
   "mass": 1.41,
   "sources": 1
  }
 },
 "gpt-5-6-terra": {
  "code_review": {
   "effort": "high",
   "avoidFrom": "xhigh",
   "evidence": "weak",
   "mass": 1.41,
   "sources": 1
  },
  "general": {
   "effort": "low",
   "avoidFrom": "medium",
   "evidence": "strong",
   "mass": 5.63,
   "sources": 8
  },
  "implementation": {
   "effort": "xhigh",
   "avoidFrom": "max",
   "evidence": "weak",
   "mass": 1.92,
   "sources": 1
  },
  "writing_docs": {
   "effort": "xhigh",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.79,
   "sources": 1
  },
  "frontend_ui": {
   "effort": "medium",
   "avoidFrom": "high",
   "evidence": "weak",
   "mass": 1.76,
   "sources": 1
  },
  "agentic_terminal": {
   "effort": "low",
   "avoidFrom": "medium",
   "evidence": "weak",
   "mass": 1.58,
   "sources": 1
  },
  "debugging": {
   "effort": "max",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.8,
   "sources": 1
  }
 },
 "gpt-5-6-luna": {
  "debugging": {
   "effort": "max",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 4.75,
   "sources": 1
  },
  "general": {
   "effort": "xhigh",
   "avoidFrom": "ultra",
   "evidence": "strong",
   "mass": 7.36,
   "sources": 5
  },
  "agentic_terminal": {
   "effort": "xhigh",
   "avoidFrom": "max",
   "evidence": "medium",
   "mass": 3.72,
   "sources": 2
  }
 },
 "gpt-5-5": {
  "general": {
   "effort": "medium",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 1.31,
   "sources": 2
  },
  "frontend_ui": {
   "effort": "low",
   "avoidFrom": null,
   "evidence": "weak",
   "mass": 0.7,
   "sources": 1
  }
 }
};
